#target aftereffects
(function () {
    if (typeof AE_CAMERA_CONFIG === "undefined") throw new Error("Run the launcher generated by make_job.py.");
    var job = AE_CAMERA_CONFIG;
    var log = [];

    function saveReport(text) {
        var f = new File(job.report);
        f.encoding = "UTF-8";
        if (!f.open("w")) throw new Error("Cannot write report: " + f.error);
        f.write(text);
        f.close();
    }

    function animate(property, data, field, axis) {
        for (var i = 0; i < data.length; i++) {
            property.setValueAtTime(data[i].frame / job.fps, axis < 0 ? data[i][field] : data[i][field][axis]);
        }
        for (var k = 1; k <= data.length; k++) {
            var incoming = k > 1 && k % 2 === 1 ? KeyframeInterpolationType.BEZIER : KeyframeInterpolationType.HOLD;
            var outgoing = k < data.length && k % 2 === 0 ? KeyframeInterpolationType.BEZIER : KeyframeInterpolationType.HOLD;
            property.setInterpolationTypeAtKey(k, incoming, outgoing);
            property.setTemporalEaseAtKey(k, [new KeyframeEase(0, 65)], [new KeyframeEase(0, 65)]);
            if (property.isSpatial) {
                property.setSpatialAutoBezierAtKey(k, false);
                property.setSpatialContinuousAtKey(k, false);
                property.setSpatialTangentsAtKey(k, [0, 0, 0], [0, 0, 0]);
            }
        }
    }

    function verify(camera, comp, data) {
        var tr = camera.property("ADBE Transform Group");
        var pos = tr.property("ADBE Position");
        var poi = tr.property("ADBE Anchor Point");
        for (var i = 0; i < data.length; i += 2) {
            for (var f = data[i].frame; f <= data[i + 1].frame; f += 0.25) {
                var aim = poi.valueAtTime(f / job.fps, true);
                for (var a = 0; a < 3; a++) {
                    var value = pos.getSeparationFollower(a).valueAtTime(f / job.fps, true);
                    if (!isFinite(value) || !isFinite(aim[a]) || Math.abs(value - data[i].position[a]) > 0.0001 ||
                        Math.abs(aim[a] - data[i].target[a]) > 0.0001) throw new Error("Camera hold drift in " + comp.name);
                }
            }
        }
        for (f = 0; f < job.frameCount; f += 0.25) {
            aim = poi.valueAtTime(f / job.fps, true);
            for (a = 0; a < 3; a++) {
                if (!isFinite(aim[a]) || !isFinite(pos.getSeparationFollower(a).valueAtTime(f / job.fps, true))) throw new Error("Invalid camera trajectory.");
            }
        }
        var video = comp.layer(2);
        if (video.timeRemapEnabled || video.parent || camera.parent) throw new Error("Unexpected video retime or rig.");
        var vt = video.property("ADBE Transform Group");
        for (i = 1; i <= vt.numProperties; i++) if (vt.property(i).numKeys || vt.property(i).expressionEnabled) throw new Error("Video plane must remain fixed.");
        log.push("PASS: " + comp.name + ": native camera/target keys, static holds, fixed plane.");
    }

    try {
        if (app.project && app.project.numItems > 0) throw new Error("Existing project is open. Save/back up it and open an empty project first.");
        if (new File(job.project).exists) throw new Error("Project output already exists.");
        if (!new File(job.media).exists) throw new Error("Prepared media is missing.");
        for (var o = 0; o < job.outputs.length; o++) {
            if (new File(job.outputs[o].file).exists) throw new Error("Movie output already exists.");
        }
        if (!app.project) app.newProject();
        app.project.gpuAccelType = GpuAccelType.SOFTWARE;
        app.project.bitsPerChannel = 8;
        var source = app.project.importFile(new ImportOptions(new File(job.media)));
        if (source.width !== job.sourceWidth || source.height !== job.sourceHeight || source.pixelAspect !== 1) throw new Error("Source dimensions/pixel aspect differ from job.");
        var duration = job.frameCount / job.fps;
        if (Math.abs(source.duration - duration) > 0.5 / job.fps || Math.abs(source.frameRate - job.fps) > 0.001) throw new Error("Prepared source timing differs from job.");
        var first = null;
        for (o = 0; o < job.outputs.length; o++) {
            var out = job.outputs[o];
            var comp = app.project.items.addComp(out.name, out.width, out.height, 1, duration, job.fps);
            comp.renderer = "ADBE Classic 3d";
            comp.bgColor = [0, 0, 0];
            comp.motionBlur = true;
            comp.shutterAngle = 90;
            comp.shutterPhase = -45;
            comp.motionBlurSamplesPerFrame = 8;
            comp.motionBlurAdaptiveSampleLimit = 16;
            comp.workAreaStart = 0;
            comp.workAreaDuration = duration;
            comp.resolutionFactor = [2, 2];
            var video = comp.layers.add(source);
            video.name = "VIDEO - fixed plane - continuous playback";
            video.threeDLayer = true;
            video.motionBlur = true;
            video.audioEnabled = source.hasAudio;
            video.outPoint = duration;
            video.property("ADBE Transform Group").property("ADBE Position").setValue([out.width / 2, out.height / 2, 0]);
            video.property("ADBE Material Options Group").property("ADBE Accepts Lights").setValue(0);
            video.comment = "No transform animation or time remapping. Prepared source plays continuously.";
            video.locked = true;
            var camera = comp.layers.addCamera("CAMERA - reading stops and fast pan/aim", [out.width / 2, out.height / 2]);
            camera.autoOrient = AutoOrientType.CAMERA_OR_POINT_OF_INTEREST;
            var tr = camera.property("ADBE Transform Group");
            tr.property("ADBE Orientation").setValue([0, 0, 0]);
            tr.property("ADBE Rotate X").setValue(0);
            tr.property("ADBE Rotate Y").setValue(0);
            tr.property("ADBE Rotate Z").setValue(0);
            camera.property("ADBE Camera Options Group").property("ADBE Camera Zoom").setValue(out.zoom);
            camera.property("ADBE Camera Options Group").property("ADBE Camera Depth of Field").setValue(0);
            var position = tr.property("ADBE Position");
            position.dimensionsSeparated = true;
            for (var a = 0; a < 3; a++) animate(position.getSeparationFollower(a), out.keys, "position", a);
            animate(tr.property("ADBE Anchor Point"), out.keys, "target", -1);
            camera.comment = "Only camera position and point of interest animate. HOLD intervals are stationary; source/cursor keeps moving.";
            for (var s = 0; s < job.shots.length; s++) {
                var shot = job.shots[s];
                var marker = new MarkerValue("CAMERA STOP - " + shot.label);
                marker.duration = (shot.endFrame - shot.startFrame) / job.fps;
                comp.markerProperty.setValueAtTime(shot.startFrame / job.fps, marker);
                if (s + 1 < job.shots.length) {
                    marker = new MarkerValue("FAST MOVE + AIM");
                    marker.duration = (job.shots[s + 1].startFrame - shot.endFrame) / job.fps;
                    comp.markerProperty.setValueAtTime(shot.endFrame / job.fps, marker);
                }
            }
            verify(camera, comp, out.keys);
            var rq = app.project.renderQueue.items.add(comp);
            rq.timeSpanStart = 0;
            rq.timeSpanDuration = duration;
            rq.setSetting("Resolution", "Full");
            var om = rq.outputModule(1), template = null;
            for (var t = 0; t < om.templates.length; t++) if (/H\.264.*15\s*Mbps/.test(om.templates[t])) template = om.templates[t];
            if (!template) throw new Error("Built-in H.264 15 Mbps template is unavailable.");
            om.applyTemplate(template);
            om.file = new File(out.file);
            if (first === null) first = comp;
        }
        first.time = Math.floor(job.shots[0].endFrame / 2) / job.fps;
        first.openInViewer().setActive();
        app.project.save(new File(job.project));
        saveReport(log.join("\n") + "\nSUCCESS: saved project; rendering still required.");
    } catch (e) {
        saveReport(log.join("\n") + "\nERROR line " + e.line + ": " + e.toString());
        throw e;
    }
}());
